/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AgendaDoticsRouteImport } from './routes/agenda[.]ics'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as SessionsSlugRouteImport } from './routes/sessions/$slug'
import { Route as SpeakersIndexRouteImport } from './routes/speakers/index'
import { Route as SpeakersSlugRouteImport } from './routes/speakers/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaDoticsRoute = AgendaDoticsRouteImport.update({
  id: '/agenda.ics',
  path: '/agenda.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSlugRoute = SessionsSlugRouteImport.update({
  id: '/sessions/$slug',
  path: '/sessions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIndexRoute = SpeakersIndexRouteImport.update({
  id: '/speakers/',
  path: '/speakers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersSlugRoute = SpeakersSlugRouteImport.update({
  id: '/speakers/$slug',
  path: '/speakers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/agenda.ics': typeof AgendaDoticsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/tickets': typeof TicketsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/news/': typeof NewsIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/agenda.ics': typeof AgendaDoticsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/tickets': typeof TicketsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/news': typeof NewsIndexRoute
  '/speakers': typeof SpeakersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/agenda.ics': typeof AgendaDoticsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsors': typeof SponsorsRoute
  '/tickets': typeof TicketsRoute
  '/news/$slug': typeof NewsSlugRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/speakers/$slug': typeof SpeakersSlugRoute
  '/news/': typeof NewsIndexRoute
  '/speakers/': typeof SpeakersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/404'
    | '/about'
    | '/agenda'
    | '/agenda.ics'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sponsors'
    | '/tickets'
    | '/news/$slug'
    | '/sessions/$slug'
    | '/speakers/$slug'
    | '/news/'
    | '/speakers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/404'
    | '/about'
    | '/agenda'
    | '/agenda.ics'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sponsors'
    | '/tickets'
    | '/news/$slug'
    | '/sessions/$slug'
    | '/speakers/$slug'
    | '/news'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/404'
    | '/about'
    | '/agenda'
    | '/agenda.ics'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sponsors'
    | '/tickets'
    | '/news/$slug'
    | '/sessions/$slug'
    | '/speakers/$slug'
    | '/news/'
    | '/speakers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AgendaRoute: typeof AgendaRoute
  AgendaDoticsRoute: typeof AgendaDoticsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorsRoute: typeof SponsorsRoute
  TicketsRoute: typeof TicketsRoute
  NewsSlugRoute: typeof NewsSlugRoute
  SessionsSlugRoute: typeof SessionsSlugRoute
  SpeakersSlugRoute: typeof SpeakersSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
  SpeakersIndexRoute: typeof SpeakersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda.ics': {
      id: '/agenda.ics'
      path: '/agenda.ics'
      fullPath: '/agenda.ics'
      preLoaderRoute: typeof AgendaDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$slug': {
      id: '/sessions/$slug'
      path: '/sessions/$slug'
      fullPath: '/sessions/$slug'
      preLoaderRoute: typeof SessionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/': {
      id: '/speakers/'
      path: '/speakers'
      fullPath: '/speakers/'
      preLoaderRoute: typeof SpeakersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$slug': {
      id: '/speakers/$slug'
      path: '/speakers/$slug'
      fullPath: '/speakers/$slug'
      preLoaderRoute: typeof SpeakersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AgendaRoute: AgendaRoute,
  AgendaDoticsRoute: AgendaDoticsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorsRoute: SponsorsRoute,
  TicketsRoute: TicketsRoute,
  NewsSlugRoute: NewsSlugRoute,
  SessionsSlugRoute: SessionsSlugRoute,
  SpeakersSlugRoute: SpeakersSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
  SpeakersIndexRoute: SpeakersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
