/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/events': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List your events
         * @description Your own events, newest start date first. Returns the base event
         *     shape — guest counts and registration questions are detail-only
         *     (see `GET /events/{slug}`).
         */
        get: operations['listEvents']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Get one event
         * @description The base event shape plus guest counts (`guest_counts`), remaining
         *     capacity (`spots_remaining`, `null` when uncapped), and the
         *     registration-question schema (`registration_questions`). Attendee
         *     answers correlate to these questions by `label`.
         */
        get: operations['getEvent']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}/attendees': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List an event's attendees
         * @description The full registration list with contact data and answers (the same
         *     data as the CSV export), oldest registration first.
         */
        get: operations['listAttendees']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}/attendees/{qr_token}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Look up one registration
         * @description Accepts the registration-level `qr_token` **or** any per-admission
         *     ticket token (what a door scanner reads off a wallet pass).
         */
        get: operations['getAttendee']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}/featured': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List speakers, sponsors, and other featured entries
         * @description The event's featured people and organizations — speakers, hosts,
         *     sponsors, and the rest of the kind set — in display order. One
         *     resource covers every kind; use `?kind=` to narrow it to speakers or
         *     sponsors.
         *
         *     An entry is either an off-platform person (its own `name`, `bio`,
         *     and `image_url`) or a Cloomba account (`username` set, with `name`
         *     and `image_url` falling back to that account's profile). `tier` is
         *     only meaningful for `kind = sponsor`; every other kind reports the
         *     default `community`. Attached materials — slides, recordings,
         *     documents — come through in `files`.
         */
        get: operations['listFeatured']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}/sessions': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List the agenda
         * @description The event's agenda sessions in running order, each carrying its
         *     speakers. A speaker's `hash` is the same handle
         *     `GET /events/{slug}/featured` returns, so the two lists join —
         *     useful for keeping an external schedule page in sync.
         *
         *     `location` is free text: a room, track, or stage.
         */
        get: operations['listSessions']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}/media': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List wall photos and videos
         * @description Photos and videos posted to the event's media wall, newest first.
         *     Use `?kind=image` for photos only.
         *
         *     `url` is the delivery URL for the original file; append resize
         *     parameters as needed. `poster_url` and `duration` are set for videos
         *     only. Each item reports the account that uploaded it.
         */
        get: operations['listMedia']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}/ticket-types': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List ticket tiers
         * @description The event's ticket tiers with prices and remaining seats, in display
         *     order. An attendee's `ticket_type.hash` matches a tier's `hash` here
         *     — join on that, not on `name`, which is not unique within an event.
         *
         *     `spots_left` is `null` for an uncapped tier. Both `spots_left` and
         *     `sold_out` are dashboard numbers rather than booking guarantees:
         *     checkout additionally holds seats while a payment is in flight.
         */
        get: operations['listTicketTypes']
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/events/{slug}/check-in': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Check a guest in
         * @description Marks a registration (and its admission) as checked in. **Requires
         *     the Pro plan and a key with the `read_write` scope** — a non-Pro
         *     account returns `403 api_pro_required`, a `read` key
         *     `403 api_scope_forbidden`. Accepts the registration token or a
         *     per-admission ticket token, same as the lookup endpoint.
         */
        post: operations['checkIn']
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        /**
         * @description Lifecycle state of the event.
         * @enum {string}
         */
        EventStatus: 'draft' | 'published' | 'cancelled' | 'completed'
        /** @enum {string} */
        EventVisibility: 'public' | 'unlisted' | 'private'
        /**
         * @description Where the event happens.
         * @enum {string}
         */
        EventFormat: 'in_person' | 'online' | 'hybrid'
        /**
         * @description Registration status.
         * @enum {string}
         */
        RsvpStatus:
            'confirmed' | 'pending_payment' | 'cancelled' | 'refunded' | 'waitlist' | 'pending_approval' | 'rejected'
        /**
         * @description Custom-question type. `options` may be single- or multi-select (see
         *     `multiple`); `checkbox` / `terms` answers are booleans; the rest are
         *     free text.
         * @enum {string}
         */
        QuestionKind: 'text' | 'options' | 'checkbox' | 'terms' | 'website' | 'social' | 'company' | 'jobtitle'
        /**
         * @description The role a featured person or organization holds on the event.
         * @enum {string}
         */
        FeaturedKind: 'speaker' | 'host' | 'performer' | 'panelist' | 'guest' | 'judge' | 'mentor' | 'sponsor'
        /**
         * @description Sponsorship level, highest first. Only meaningful for
         *     `kind = sponsor`; every other kind reports `community`.
         * @enum {string}
         */
        SponsorTier: 'platinum' | 'gold' | 'silver' | 'bronze' | 'community'
        /**
         * @description What an attached file is.
         * @enum {string}
         */
        FeaturedFileKind: 'slides' | 'recording' | 'document' | 'other'
        /** @enum {string} */
        MediaKind: 'image' | 'video'
        /**
         * @description `hidden` tiers are not offered on the public event page.
         * @enum {string}
         */
        TicketTypeVisibility: 'public' | 'hidden'
        /** @description Physical location. All fields are null for a purely online event. */
        Location: {
            name: string | null
            address: string | null
            city: string | null
            /**
             * @description ISO 3166-1 alpha-2 country code.
             * @example SK
             */
            country: string | null
            /** Format: double */
            lat: number | null
            /** Format: double */
            lng: number | null
        }
        /** @description The base event shape, as returned by the list endpoint. */
        Event: {
            /** @description Stable public id used in URLs and API paths. */
            hash: string
            slug: string
            title: string
            /** @description Markdown, the same encoding the app renders. */
            description: string | null
            status: components['schemas']['EventStatus']
            visibility: components['schemas']['EventVisibility']
            format: components['schemas']['EventFormat']
            /** Format: date-time */
            starts_at: string
            /** Format: date-time */
            ends_at: string | null
            /**
             * @description IANA timezone; render `starts_at` / `ends_at` in this zone for wall-clock time.
             * @example Europe/Bratislava
             */
            timezone: string
            location: components['schemas']['Location']
            /** Format: uri */
            online_url: string | null
            /** @description Admission capacity; `null` when uncapped. */
            capacity: number | null
            /** @description Whether free registrations need organizer approval. */
            require_approval: boolean
            /** Format: uri */
            cover_url: string | null
            /**
             * Format: uri
             * @description The event's public page.
             */
            url: string
            /** Format: date-time */
            created_at: string
            /** Format: date-time */
            updated_at: string
        }
        /** @description The base event shape plus detail-only enrichments. */
        EventDetail: components['schemas']['Event'] & {
            guest_counts: components['schemas']['GuestCounts']
            /** @description Capacity minus confirmed admissions; `null` when uncapped. */
            spots_remaining: number | null
            registration_questions: components['schemas']['RegistrationQuestion'][]
        }
        /**
         * @description Registration tallies by status. `guests` counts registrations;
         *     `tickets` counts admissions (a confirmed order holds one row per
         *     admission; a pending request counts `1 + plus_ones`).
         */
        GuestCounts: {
            confirmed: components['schemas']['CountPair']
            pending_approval: components['schemas']['CountPair']
            pending_payment: components['schemas']['CountPair']
            waitlist: components['schemas']['CountPair']
            checked_in: components['schemas']['CountPair']
        }
        CountPair: {
            guests: number
            tickets: number
        }
        /** @description A custom registration question. Answers correlate by `label`. */
        RegistrationQuestion: {
            label: string
            /** @description Optional supporting text shown under the question, in Markdown. `null` when unset. */
            description: string | null
            kind: components['schemas']['QuestionKind']
            required: boolean
            /** @description Choice list for `kind = options`; `null` otherwise. */
            options: string[] | null
            /** @description `kind = options` only: true when more than one choice may be selected. */
            multiple: boolean
        }
        TicketTypeRef: {
            /**
             * @description Stable public id of the tier. Join to `GET /events/{slug}/ticket-types`
             *     on this — `name` is not unique within an event.
             */
            hash: string
            name: string
            /** @description Integer minor units (cents). */
            price_cents: number
            /** @description ISO 4217 currency code. */
            currency: string
        }
        /** @description One per-admission door credential. */
        Ticket: {
            token: string
            /** Format: date-time */
            checked_in_at: string | null
        }
        /**
         * @description One custom-question answer, decoded to its natural type: `options` →
         *     array of strings, `checkbox` / `terms` → boolean, everything else →
         *     string or null.
         */
        Answer: {
            label: string
            kind: components['schemas']['QuestionKind']
            /** @description String, array of strings, boolean, or null depending on `kind`. */
            value: string | string[] | boolean | null
        }
        /** @description A registration with full contact data and answers. */
        Attendee: {
            qr_token: string
            status: components['schemas']['RsvpStatus']
            attendee: {
                username: string
                display_name: string | null
            }
            /** @description The consented per-registration email — never the account email. */
            email: string | null
            phone: string | null
            note: string | null
            plus_ones: number
            ticket_type: components['schemas']['TicketTypeRef']
            /** @description Net amount paid after discount */
            price_cents_paid: number
            /** @description Amount a coupon took off */
            discount_cents: number
            coupon_code: string | null
            /** @description ISO 4217 currency code. */
            currency: string
            /** Format: date-time */
            checked_in_at: string | null
            ticket_count: number
            checked_in_tickets: number
            tickets: components['schemas']['Ticket'][]
            answers: components['schemas']['Answer'][]
            /** Format: date-time */
            created_at: string
        }
        /** @description The registration's check-in state after a successful check-in. */
        CheckInResult: {
            qr_token: string
            status: components['schemas']['RsvpStatus']
            /** Format: date-time */
            checked_in_at: string | null
            ticket_count: number
            checked_in_tickets: number
            tickets: components['schemas']['Ticket'][]
        }
        /** @description A file attached to a featured entry — slides, a recording, a document. */
        FeaturedFile: {
            kind: components['schemas']['FeaturedFileKind']
            /** Format: uri */
            url: string | null
            mime_type: string
            /** @description Size in bytes. */
            size: number
            title: string | null
            /** @description Display order within the entry. */
            position: number
        }
        /** @description A featured person or organization on the event. */
        Featured: {
            /** @description Stable public id. Session speakers cite the same value. */
            hash: string
            kind: components['schemas']['FeaturedKind']
            /**
             * @description The entry's own name, falling back to the linked account's display
             *     name when the entry is a Cloomba user.
             */
            name: string | null
            /** @description A short role or title line. */
            headline: string | null
            bio: string | null
            /** Format: uri */
            link: string | null
            /**
             * Format: uri
             * @description The entry's own image, falling back to the linked account's avatar.
             */
            image_url: string | null
            tier: components['schemas']['SponsorTier']
            /** @description Display order within the kind. */
            position: number
            /** @description The linked Cloomba account, or `null` for an off-platform entry. */
            username: string | null
            files: components['schemas']['FeaturedFile'][]
        }
        /**
         * @description A speaker on an agenda session — the slim view of a featured entry.
         *     `hash` matches the entry in `GET /events/{slug}/featured`.
         */
        SessionSpeaker: {
            hash: string
            kind: components['schemas']['FeaturedKind']
            name: string | null
            headline: string | null
            /** Format: uri */
            image_url: string | null
            username: string | null
        }
        /** @description One agenda session or talk. */
        Session: {
            /** @description Stable public id */
            hash: string
            title: string
            description: string | null
            /** Format: date-time */
            starts_at: string
            /** Format: date-time */
            ends_at: string
            /** @description Room */
            location: string | null
            /** @description Tie-breaker for sessions starting at the same time. */
            position: number
            speakers: components['schemas']['SessionSpeaker'][]
        }
        /** @description One photo or video from the event's media wall. */
        MediaItem: {
            /** @description Stable public id of the media item. */
            ref: string
            kind: components['schemas']['MediaKind']
            /**
             * Format: uri
             * @description Delivery URL for the original file.
             */
            url: string | null
            /**
             * Format: uri
             * @description Video poster frame; `null` for photos.
             */
            poster_url: string | null
            mime_type: string
            /** @description Size in bytes. */
            size: number
            width: number
            height: number
            /** @description Video length in seconds; `null` for photos. */
            duration: number | null
            caption: string | null
            /**
             * Format: date-time
             * @description When the photo was taken, when the file carried that metadata.
             */
            taken_at: string | null
            uploader: {
                username: string
                display_name: string | null
            } | null
            /** Format: date-time */
            created_at: string
        }
        /** @description A ticket tier with its price and remaining seats. */
        TicketType: {
            /** @description Stable public id. Attendee rows cite this value. */
            hash: string
            /** @description Not unique within an event — join on `hash`. */
            name: string
            description: string | null
            /** @description Integer minor units (cents). */
            price_cents: number
            /** @description ISO 4217 currency code. */
            currency: string
            /** @description Seats allocated to this tier; `null` when uncapped. */
            quantity: number | null
            /** @description Remaining seats; `null` when uncapped. */
            spots_left: number | null
            sold_out: boolean
            /** Format: date-time */
            sales_starts_at: string | null
            /** Format: date-time */
            sales_ends_at: string | null
            visibility: components['schemas']['TicketTypeVisibility']
            /** @description Display order. */
            position: number
        }
        /** @description The full set — not paginated; an event's featured list is inherently small. */
        FeaturedList: {
            items: components['schemas']['Featured'][]
            total: number
        }
        /** @description The full agenda — not paginated. */
        SessionList: {
            items: components['schemas']['Session'][]
            total: number
        }
        MediaList: {
            items: components['schemas']['MediaItem'][]
            /** @description Total wall items matching the query. */
            total: number
            limit: number
            offset: number
        }
        /** @description The full tier set — not paginated. */
        TicketTypeList: {
            items: components['schemas']['TicketType'][]
            total: number
        }
        EventList: {
            items: components['schemas']['Event'][]
            /** @description Total events matching the query. */
            total: number
            limit: number
            offset: number
        }
        AttendeeList: {
            items: components['schemas']['Attendee'][]
            /** @description Total registrations matching the query. */
            total: number
            checked_in_count: number
            limit: number
            offset: number
        }
        /** @description Error body. Branch on `code`, never on `message`. */
        Error: {
            /** @enum {string} */
            code:
                | 'api_key_invalid'
                | 'api_key_revoked'
                | 'api_scope_forbidden'
                | 'api_pro_required'
                | 'event_not_found'
                | 'rsvp_not_found'
                | 'validation_failed'
                | 'rate_limited'
            /** @description Human-readable */
            message: string
            /** @description Optional structured context (e.g. `fields` for validation errors). */
            details?: Record<string, never>
        }
    }
    responses: {
        /** @description Missing, invalid, or revoked API key (`api_key_invalid`, `api_key_revoked`). */
        Unauthorized: {
            headers: {
                [name: string]: unknown
            }
            content: {
                /**
                 * @example {
                 *       "code": "api_key_invalid",
                 *       "message": "Invalid API key."
                 *     }
                 */
                'application/json': components['schemas']['Error']
            }
        }
        /**
         * @description The key can't reach this resource — an event outside the key's
         *     scope, a write with a `read`-only key (`api_scope_forbidden`), or
         *     a write from a non-Pro account (`api_pro_required`).
         */
        Forbidden: {
            headers: {
                [name: string]: unknown
            }
            content: {
                /**
                 * @example {
                 *       "code": "api_scope_forbidden",
                 *       "message": "This API key does not have access to this resource."
                 *     }
                 */
                'application/json': components['schemas']['Error']
            }
        }
        /** @description No such event (`event_not_found`). */
        EventNotFound: {
            headers: {
                [name: string]: unknown
            }
            content: {
                /**
                 * @example {
                 *       "code": "event_not_found",
                 *       "message": "Event not found."
                 *     }
                 */
                'application/json': components['schemas']['Error']
            }
        }
        /** @description No registration matches that token (`rsvp_not_found`). */
        RsvpNotFound: {
            headers: {
                [name: string]: unknown
            }
            content: {
                /**
                 * @example {
                 *       "code": "rsvp_not_found",
                 *       "message": "RSVP not found."
                 *     }
                 */
                'application/json': components['schemas']['Error']
            }
        }
        /** @description The request is invalid (`validation_failed`). `details.fields` names the offending fields. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown
            }
            content: {
                /**
                 * @example {
                 *       "code": "validation_failed",
                 *       "message": "The request is invalid.",
                 *       "details": {
                 *         "fields": {
                 *           "status": "must be one of: confirmed, pending_payment, cancelled, refunded, waitlist, pending_approval, rejected"
                 *         }
                 *       }
                 *     }
                 */
                'application/json': components['schemas']['Error']
            }
        }
        /** @description Too many requests — 60/min per key or 10,000/day per account (`rate_limited`). */
        RateLimited: {
            headers: {
                [name: string]: unknown
            }
            content: {
                /**
                 * @example {
                 *       "code": "rate_limited",
                 *       "message": "Too many requests. Please try again later."
                 *     }
                 */
                'application/json': components['schemas']['Error']
            }
        }
    }
    parameters: {
        /** @description The event's URL slug. */
        Slug: string
        /** @description Page size (default 50, max 100). */
        Limit50: number
        /** @description Page size (default 100, max 500). */
        Limit100: number
        /** @description Number of items to skip. */
        Offset: number
    }
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    listEvents: {
        parameters: {
            query?: {
                /** @description Page size (default 50, max 100). */
                limit?: components['parameters']['Limit50']
                /** @description Number of items to skip. */
                offset?: components['parameters']['Offset']
            }
            header?: never
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description A page of events. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['EventList']
                }
            }
            401: components['responses']['Unauthorized']
            429: components['responses']['RateLimited']
        }
    }
    getEvent: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description The event. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['EventDetail']
                }
            }
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['EventNotFound']
            429: components['responses']['RateLimited']
        }
    }
    listAttendees: {
        parameters: {
            query?: {
                /** @description Page size (default 100, max 500). */
                limit?: components['parameters']['Limit100']
                /** @description Number of items to skip. */
                offset?: components['parameters']['Offset']
                /**
                 * @description Optional filter by registration status. An unknown value returns
                 *     `400 validation_failed` rather than an empty list.
                 */
                status?: components['schemas']['RsvpStatus']
            }
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description A page of registrations. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['AttendeeList']
                }
            }
            400: components['responses']['ValidationFailed']
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['EventNotFound']
            429: components['responses']['RateLimited']
        }
    }
    getAttendee: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
                /** @description The registration token or a per-admission ticket token. */
                qr_token: string
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description The registration. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['Attendee']
                }
            }
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['RsvpNotFound']
            429: components['responses']['RateLimited']
        }
    }
    listFeatured: {
        parameters: {
            query?: {
                /**
                 * @description Optional filter by role. An unknown value returns
                 *     `400 validation_failed` rather than an empty list.
                 */
                kind?: components['schemas']['FeaturedKind']
            }
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description The event's featured entries. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['FeaturedList']
                }
            }
            400: components['responses']['ValidationFailed']
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['EventNotFound']
            429: components['responses']['RateLimited']
        }
    }
    listSessions: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description The event's agenda. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['SessionList']
                }
            }
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['EventNotFound']
            429: components['responses']['RateLimited']
        }
    }
    listMedia: {
        parameters: {
            query?: {
                /** @description Page size (default 100, max 500). */
                limit?: components['parameters']['Limit100']
                /** @description Number of items to skip. */
                offset?: components['parameters']['Offset']
                /**
                 * @description Optional filter by media type. An unknown value returns
                 *     `400 validation_failed` rather than an empty list.
                 */
                kind?: components['schemas']['MediaKind']
            }
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description A page of wall media. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['MediaList']
                }
            }
            400: components['responses']['ValidationFailed']
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['EventNotFound']
            429: components['responses']['RateLimited']
        }
    }
    listTicketTypes: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description The event's ticket tiers. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['TicketTypeList']
                }
            }
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['EventNotFound']
            429: components['responses']['RateLimited']
        }
    }
    checkIn: {
        parameters: {
            query?: never
            header?: never
            path: {
                /** @description The event's URL slug. */
                slug: components['parameters']['Slug']
            }
            cookie?: never
        }
        requestBody: {
            content: {
                'application/json': {
                    /** @description The registration token or a per-admission ticket token. */
                    qr_token: string
                }
            }
        }
        responses: {
            /** @description The updated check-in state. */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    'application/json': components['schemas']['CheckInResult']
                }
            }
            400: components['responses']['ValidationFailed']
            401: components['responses']['Unauthorized']
            403: components['responses']['Forbidden']
            404: components['responses']['RsvpNotFound']
            429: components['responses']['RateLimited']
        }
    }
}
